# Generated by Django 5.1.3 on 2024-12-10 19:14

import zarchive.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[
                zarchive.validators.AlphaValidator()]),
        ),
    ]
