# Generated by Django 5.1.3 on 2024-12-05 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publish',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
