# Generated by Django 5.1.3 on 2024-12-10 20:20

import cloudinary.models
import zarchive.books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('books', '0005_alter_book_cover_image'), ('books', '0006_alter_book_pages'), ('books', '0007_alter_book_year_of_publish'), ('books', '0008_alter_book_pages_alter_book_year_of_publish')]

    dependencies = [
        ('books', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(validators=[zarchive.books.validators.MinimalNumberValidator(0, 'Pages should be more than 0'), zarchive.books.validators.MaximalNumberValidator(10000, 'Pages should be less than 10000')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_publish',
            field=models.PositiveSmallIntegerField(validators=[zarchive.books.validators.MinimalNumberValidator(1800, 'The year should be greater than 1800'), zarchive.books.validators.MaximalNumberValidator(2100, 'The year should be less than 2100')]),
        ),
    ]
