# Generated by Django 5.1.3 on 2024-12-10 19:14

import zarchive.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[zarchive.validators.AlphaValidator()]),
        ),
    ]
