# Generated by Django 5.1.3 on 2024-11-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_words', models.CharField(max_length=120)),
                ('translated_word', models.CharField(max_length=120)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionaries', to='books.book')),
            ],
        ),
    ]
